<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="COMPND-LTP-237" ignored="0" name="Test" tests="1" failures="1" timestamp="07 May 2020 14:39:08 GMT" time="102.142" errors="0">
  <testcase name="maxCartCount" time="56.124" classname="Script.UserProductPurchase">
    <failure type="java.lang.AssertionError" message="expected [10] but found [18]">
      <![CDATA[java.lang.AssertionError: expected [10] but found [18]
at feature.taskfeature.CartCount(taskfeature.java:236)
at Script.UserProductPurchase.maxCartCount(UserProductPurchase.java:30)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
... Removed 22 stack frames]]>
    </failure>
  </testcase> <!-- maxCartCount -->
</testsuite> <!-- Test -->
